module.exports = {
  'soma': 1,
  'south beach': 1,
  'soma / south beach':1,
  'USF': 2,
  'panhandle': 2,
  'bernal heights': 3,
  'castro': 4,
  'upper market': 4,
  'cole valley': 5,
  'ashbury heights': 5,
  'downtown': 6,
  'civic': 6,
  'van ness': 6,
  'exelsior': 7,
  'outer mission': 7,
  'financial district': 8,
  'glen park': 9,
  'lower haight': 10,
  'haight-ashbury': 11,
  'haight ashbury': 11,
  'hayes valley': 12,
  'ingleside': 13,
  'sfsu': 13,
  'ccsf': 13,
  'inner richmond': 14,
  'inner sunset': 15,
  'ucsf': 15,
  'laurel heights': 16,
  'presidio': 16,
  'marina': 17,
  'cow hollow': 17,
  'marina/cow hollow':17,
  'mission': 18,
  'mission district': 18,
  'nob hill': 19,
  'lower nob hill': 20,
  'noe valley': 21,
  'north beach': 22,
  "fisherman's wharf":22,
  'north beach/telegraph hill':22,
  'north beach / telegraph hill':22,
  'sunset / parkside':28,
  'telegraph hill': 22,
  'pacific heights': 23,
  'lower pac heights': 24,
  'potrero hill': 25,
  'richmond': 26,
  'seacliff': 26,
  'russian hill': 27,
  'sunset': 28,
  'parkside': 28,
  'twin peaks': 29,
  'diamond heights': 29,
  'western addition': 30,
  'bayview': 110,
  'west portal': 114,
  'forest hill': 114,
  'visitacion valley': 118,
  'alamo square': 149,
  'nopa': 149,
  'tenderloin': 156,
  'treasure island': 157,
  'portola district': 164,
};